kubernetesClusterDomain: cluster.local
zerokNextDashboard:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  replicas: 1
  type: ClusterIP
  zerokNextDashboard:
    image:
      repository: ""
      tag: ""
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
