kubernetesClusterDomain: cluster.local
zerokNextDashboard:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  replicas: 1
  type: ClusterIP
  zerokNextDashboard:
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
image:
  repository: us-west1-docker.pkg.dev/zerok-dev/zerok-dashboard/zerok-next-dashboard
  tag: dev
  imagePullPolicy: Always
global:
  host: ""
  domain: ""
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/zerok-dashboard"
   
