apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zerok-glance-dashboard"
  labels:
  {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zerokGlanceDashboard.replicas }}
  selector:
    matchLabels:
      app: "zerok-glance-dashboard"
    {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: "zerok-glance-dashboard"
      {{- include "helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ index .Values.global.dockerBase}}/{{ index .Values.image.repo}}:{{ index .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: "zerok-glance-dashboard"
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.zerokGlanceDashboard.zerokGlanceDashboard.resources |
          nindent 10 }}