apiVersion: v1
kind: Service
metadata:
  name: 'zerok-glance-dashboard'
  labels:
  {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zerokGlanceDashboard.type }}
  selector:
    app: 'zerok-glance-dashboard'
  {{- include "helm-charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.zerokGlanceDashboard.ports | toYaml | nindent 2 -}}