name: release
on:
  push:
    tags: #r/<CLUSTER-NAME>/<DOCKER-TAG-OR-VERSION>
      - 'dev/**'
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: 'Docker Image Tag'
        required: true
        default: 'dev'
      GKE_CLUSTER:
        description: 'Cluster Name'
        required: true
        default: 'devcloud01'
      
env:
  NS: ${{ vars.NS }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
  CLERK_PUBLISHABLE_KEY: ${{ vars.CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  BUILD_AND_PUSH: true
  DEPLOY: true

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-dev-init.yml@main
    with:
      GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  
  get-flagsmith-id:
      needs: init
      runs-on: zk-self-hosted
      outputs:
        FLAGSMITH_KEY: ${{ steps.extractFlagId.outputs.FLAGSMITH_KEY }}
      env:
        CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      environment:
        name: ${{ needs.init.outputs.ENVIRONMENT }}
      steps:
        - name: Get flag env for cloud
          id: extractFlagId
          run: |
            CLUSTERNAME_CAPITAL=$(echo "$CLUSTERNAME" | tr '[:lower:]' '[:upper:]')
            echo "CLUSTERNAME_CAPITAL=$CLUSTERNAME_CAPITAL"
            FLAGSMITH_KEY=${CLUSTERNAME_CAPITAL}_FLAGSMITH_KEY
            echo FLAGSMITH_KEY=$FLAGSMITH_KEY >> $GITHUB_OUTPUT
            echo "FLAGSMITH_KEY set in this step: $FLAGSMITH_KEY"  # Debugging line
            echo "$FLAGSMITH_KEY"
  ##############
  print-envs:
    needs: [init, get-flagsmith-id]
    runs-on: zk-self-hosted
    env:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      FLAGSMITH_KEY: ${{ needs.get-flagsmith-id.outputs.FLAGSMITH_KEY }}
    environment:
      name: ${{ needs.init.outputs.ENVIRONMENT }}
    steps:
      - name: Print environment vars
        run: |
          echo "GIT_TAG=$GIT_TAG"
          echo "CLUSTER_NAME=$CLUSTERNAME"
          echo "DOCKER_TAG=$VERSION"
          echo "GKE_ZONE=$GKE_ZONE"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "K8S_NAMESPACE=$NS"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "DOMAIN_NAME=$DOMAIN_NAME"
          echo "FLAGSMITH_KEY=$FLAGSMITH_KEY"

  ##############
  build-and-push:
    runs-on: zk-self-hosted
    needs: [init, get-flagsmith-id]
    environment:
      name: ${{ needs.init.outputs.ENVIRONMENT }}
    env:
      FLAGSMITH_ID: ${{ vars[format('{0}', needs.get-flagsmith-id.outputs.FLAGSMITH_KEY)] }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      DOCKER_FILE_NAME: "Dockerfile"
      MAKE_TARGET: "default"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git for private modules
        run: git config --global url."https://$TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build
        run: |
          make ${{ inputs.MAKE_TARGET }}

      - name: Test
        run: |
          ls

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY_DEV }}'

      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - name: Docker build
        run: |-
          docker build -f $DOCKER_FILE_NAME --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" .

      - name: Docker Tag
        run: |-
          docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

      - name: Docker push
        run: |-
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$GITHUB_SHA"
          docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$DOCKER_IDENTIFIER/$APP_NAME:$VERSION"

  deploy:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-deploy.yml@main
    with:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      MIGRATION_VERSION: ${{ needs.init.outputs.VERSION }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      HELM_ARGS: "--recreate-pods"
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SAx_KEY_DEV }}
    needs: [init, get-flagsmith-id, build-and-push]
