name: release
on:
  push:
    tags: #r/<CLUSTER-NAME>/<DOCKER-TAG-OR-VERSION>
      - 'dev/**'
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: 'Docker Image Tag'
        required: true
        default: 'dev'
      GKE_CLUSTER:
        description: 'Cluster Name'
        required: true
        default: 'devcloud01'
      
env:
  NS: ${{ vars.NS }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  BUILD_AND_PUSH: true
  DEPLOY: true

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-dev-init.yml@main
    with:
      GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  
  get-flagsmith-id:
      needs: init
      runs-on: zk-self-hosted
      outputs:
        FLAGSMITH_ID: ${{ steps.extractFlagId.outputs.FLAGSMITH_ID }}
      env:
        CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      environment:
        name: ${{ needs.init.outputs.ENVIRONMENT }}
      steps:
        - name: Get flag env for cloud
          id: extractFlagId
          run: |
            CLUSTERNAME_CAPITAL=$(echo "$CLUSTERNAME" | tr '[:lower:]' '[:upper:]')
            echo "CLUSTERNAME_CAPITAL=$CLUSTERNAME_CAPITAL"
            FLAGSMITH_ID=${CLUSTERNAME_CAPITAL}_FLAGSMITH_ID
            echo FLAGSMITH_ID=$FLAGSMITH_ID >> $GITHUB_OUTPUT
            echo "FLAGSMITH_ID set in this step: $FLAGSMITH_ID"  # Debugging line
            echo "$FLAGSMITH_ID"
  ##############
  print-envs:
    needs: [init, get-flagsmith-id]
    runs-on: zk-self-hosted
    env:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      FLAGSMITH_ID: ${{ needs.get-flag-id.outputs.FLAGSMITH_ID }}
    environment:
      name: ${{ needs.init.outputs.ENVIRONMENT }}
    steps:
      - name: Print environment vars
        run: |
          echo "GIT_TAG=$GIT_TAG"
          echo "CLUSTER_NAME=$CLUSTERNAME"
          echo "DOCKER_TAG=$VERSION"
          echo "GKE_ZONE=$GKE_ZONE"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "K8S_NAMESPACE=$NS"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "DOMAIN_NAME=$DOMAIN_NAME"
          echo "FLAGSMITH_ID=$FLAGSMITH_ID"

  ##############
  build-and-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-build-push.yml@feature-flag-action
    with:
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.CLUSTERNAME }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      MAKE_TARGET: "default"
      FLAGSMITH_ID_VAR: ${{ needs.get-flag-id.outputs.FLAGSMITH_ID }}
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: [init, get-flagsmith-id]

  deploy:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-deploy.yml@main
    with:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      MIGRATION_VERSION: ${{ needs.init.outputs.VERSION }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      HELM_ARGS: "--recreate-pods"
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: [init, get-flagsmith-id, build-and-push]
