name: build-push
on:
  push:
    tags: #r/<CLUSTER-NAME>/<DOCKER-TAG-OR-VERSION>
      - 'push/**'
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: 'Docker Image Tag'
        required: true
        default: 'dev'
      GKE_CLUSTER:
        description: 'Cluster Name'
        required: true
        default: 'devcloud01'
      
env:
  NS: ${{ vars.NS }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  BUILD_AND_PUSH: true
  DEPLOY: true

jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-dev-init.yml@main
    with:
      GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  print-envs:
    needs: init
    runs-on: zk-self-hosted
    env:
      CLUSTERNAME: ${{ needs.init.outputs.CLUSTERNAME }}
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
    environment:
      name: ${{ needs.init.outputs.ENVIRONMENT }}
    steps:
      - name: Print environment vars
        run: |
          echo "GIT_TAG=$GIT_TAG"
          echo "CLUSTER_NAME=$CLUSTERNAME"
          echo "DOCKER_TAG=$VERSION"
          echo "GKE_ZONE=$GKE_ZONE"
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "K8S_NAMESPACE=$NS"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "DOMAIN_NAME=$DOMAIN_NAME"

  ##############
  build-and-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-build-push.yml@main
    with:
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.CLUSTERNAME }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      MAKE_TARGET: "default"
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_DEV }}
    needs: init